name: Deploy test

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  build-migration:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
